include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    
    curly_braces_in_flow_control_structures: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true

    # Flutter specific rules
    avoid_print: true
    use_key_in_widget_constructors: true
    use_full_hex_values_for_flutter_colors: true
    sized_box_for_whitespace: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    use_decorated_box: true
    use_colored_box: true
    use_super_parameters: true

    # Code quality rules
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    use_build_context_synchronously: true
    use_rethrow_when_possible: true
    valid_regexps: true

    # Documentation rules
    package_api_docs: false
    public_member_api_docs: false
    slash_for_doc_comments: true
    unnecessary_late: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_null_aware_assignments: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    unnecessary_underscores: true
